# NumPy (Numerical Python)

In [2]:
'''
List value store
NumPy used for mathematical calculation
NumPy is based on C Programming

Pandas, Scikit-learn, Matplotlib
'''

'\nList value store\nNumPy used for mathematical calculation\nNumPy is based on C Programming\n\nPandas, Scikit-learn, Matplotlib\n'

In [8]:
import numpy as np

In [38]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [40]:
c = a + b
c

[1, 2, 3, 4, 5, 6, 7, 8]

In [42]:
print(type(a))
print(type(b))

<class 'list'>
<class 'list'>


In [44]:
a_num = np.array(a)
b_num = np.array(b)

In [46]:
print(type(a_num))
print(type(b_num))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [51]:
c_num = a_num - b_num
c_num

array([-4, -4, -4, -4])

# 1D Array

In [54]:
oneD_array = np.array([1, 2, 3, 4, 5])
oneD_array

array([1, 2, 3, 4, 5])

# 2D Array (Multi-Dimensional Array)

In [58]:
twoD_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
twoD_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Zeros, Ones, arange

In [ ]:
'''
zeros
ones

1st argument -> number of rows and columns
2nd argument -> data type (integer / float)
'''

In [67]:
zero_array = np.zeros(5, dtype=int) # column -> 1 row and 5 columns
zero_array

array([0, 0, 0, 0, 0])

In [71]:
one_array = np.ones(5, dtype=int)
one_array

array([1, 1, 1, 1, 1])

In [73]:
# Binary Classifiction -> image classification
# Dog, Cat

In [81]:
zero_array2 = np.zeros((5, 2), dtype=int)
zero_array2

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [83]:
one_array2 = np.ones((5, 2), dtype=int)
one_array2

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [95]:
# range -> start, stop, step
# for i in range(10):
#     print(i)
num_gen = np.arange(1, 10, 2)
num_gen

array([1, 3, 5, 7, 9])

In [104]:
# size, shape, ndim
one_array2.size

10

In [100]:
one_array2.shape

(5, 2)

In [102]:
one_array2.ndim

2

In [106]:
zero_array.ndim

1

# Reshape and Ravel

In [110]:
numbers = np.arange(1, 61)

In [112]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [114]:
num = numbers.reshape(6, 10)

In [116]:
num

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [118]:
num_rav = num.ravel()

In [120]:
num_rav

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

# Slicing

In [124]:
num = numbers.reshape(6, 10)
num

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [128]:
# 1 -> Row, 4 column
# 1, 4 -> row
num[1:4, 1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [132]:
num[3:4, 4:5]

array([[35]])

# Boolean Indexing, Array Broadcasting

In [135]:
numbers = np.arange(1, 10)
numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
filter_numbers = numbers > 5
filter_numbers

array([False, False, False, False, False,  True,  True,  True,  True])

In [139]:
numbers[filter_numbers]

array([6, 7, 8, 9])

In [141]:
numbers[numbers>5]

array([6, 7, 8, 9])

In [143]:
names = ["Ram", "Ram", "Hari", 'Shyam', "Gita"]
names_array = np.array(names)
names_array

array(['Ram', 'Ram', 'Hari', 'Shyam', 'Gita'], dtype='<U5')

In [145]:
filter_name = names_array == 'Ram'
filter_name

array([ True,  True, False, False, False])

In [147]:
names_array[filter_name]

array(['Ram', 'Ram'], dtype='<U5')

# Brodcasting

In [177]:
'''
Rules of brodcasting
---------------------------
1. Number of rows and columns should be equal
2. Either row or column dimension should be one
'''

'\nRules of brodcasting\n---------------------------\n1. Number of rows and columns should be equal\n2. Either row or column dimension should be one\n'

In [179]:
num1 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
num1.shape

(3, 4)

In [193]:
num2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
num2.shape

(2, 4)

In [197]:
num1 * num2

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 